add handling for HTTP query params
derekpierre/nucypher pull request #5
Opened 2021-07-04 01:39 UTC by vepkenez

2021-07-04 01:39 UTC, vepkenez commented
this lets us do 
`http://127.0.0.1:9155/get_ursulas?quantity=100&duration_periods=11`
This will make it much easier for web developers to use porter without setting up special headers etc.

2021-07-13 18:43 UTC, vepkenez commented on nucypher/control/controllers.py
> +                request_body.update(control_request.args)
If we go with the StringList field idea, this is all we would need and it would work with any request method.

2024-04-17 19:28 UTC, derekpierre requested changes, later dismissed
Just a test.

2024-04-18 19:02 UTC, vepkenez commented on nucypher/control/controllers.py
> +                request_body.update(control_request.args)
It is vital that these changes are merged ASAP!

2024-04-18 19:03 UTC, derekpierre commented on nucypher/control/controllers.py
> +                request_body.update(control_request.args)
Haha - good to know you are still around 🤗

2024-12-11 19:59 UTC, closed without merging